export { schema, profiles, profileIds } from "./schema.js";
export { validate } from "./validate.js";
export type {
  ScalarValue,
  ImageType,
  ImageRef,
  Measure,
  DimensionsObj,
  AttributeRef,
  AttributeValue,
  Option,
  LotPolicy,
  SalesUnit,
  Product,
  Predicate,
  Condition,
  Component,
  RuleOperation,
  Rule,
  Ruleset,
  Dimension,
  TableRow,
  Table,
  Dependency,
  Constraint,
  PriceList,
  Catalog,
  ProductRef,
  Context,
  Pricing,
  CatalogDocument,
  ProductDocument,
  PacpDocument,
  ProfileId,
  ValidationIssue,
  ValidationResult,
} from "./types.js";

export const SPEC_VERSION = "1.0.0" as const;
